### ISSUE TITLE
FileNotFoundException (File used by another process)

### ISSUE THREAD

**Issue by dl1ely** [cryogen-project/cryogen-core#15]
I am using Sublime Text to edit posts. Occasionally, i get this when saving in ST with `lein ring server` running:

    Exception in thread "Thread-0" java.io.FileNotFoundException:     resources\templates\asc\posts\.suble12.tmp (The process cannot access the file because it is being     used by another process)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at pandect.algo.md5$eval6586$fn__6587.invoke(md5.clj:60)
        at pandect.algo.md5$eval6559$fn__6560$G__6550__6565.invoke(md5.clj:9)
        at pandect.algo.md5$eval6614$md5__6627.invoke(md5.clj:116)
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:598)
        at clojure.core$next.invoke(core.clj:64)
        at clojure.core$zipmap.invoke(core.clj:2791)
        at cryogen_core.watcher$checksums.invoke(watcher.clj:16)
        at cryogen_core.watcher$watch_assets.invoke(watcher.clj:27)
        at cryogen_core.watcher$start_watcher_BANG_$fn__10797.invoke(watcher.clj:33)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)

I see it seems to have something to do with the temp file ST drops in the `posts` directory, and that the exception originates from somewhere inside pandect.algo.md5, but perhaps cryogen can do something about it?

After the exception, `lein ring server` does not continue watching the directory :disappointed:

**Comment by lacarmen** [comment]
I believe you need to add the regex for the temp files generated by ST to `ignored-files` in the config. Another user had a similar problem with emacs interlock files.

**Comment by dl1ely** [comment]
Thanks, will try that. But i still wonder if there is no better way. Please
leave this issue open, i want to have a look at it.

**Comment by dl1ely** [comment]
I thought to let the checksummer only look for .md files in md and .asc in asc, automatically ignoring all other files, but that seems to be a too complicated move. I added *.tmp to the list of ignored files, which solved my problem, too.
